name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  format-test:
    name: Format / Unit Tests / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        # Tests currently fail for 3.8 and 3.9.
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/ml_croissant
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install library
      run: pip install .[dev]

    - name: PyTest
      run: pytest .

    - name: PyLint
      run: pylint **/*.py

    # Pyflakes can see unused imports
    - name: PyFlakes
      run: pyflakes .

  pytype-test:
    name: PyType
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/ml_croissant
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies except ml_croissant itself
      run: pip install absl-py etils[epath] networkx pandas pytest pytype rdflib requests tqdm

    - name: PyType
      run: pytype --jobs="$(grep -c ^processor /proc/cpuinfo)" --config=./pyproject.toml

  validation-test:
    name: Validation / JSON-LD Tests / Python 3.11
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/ml_croissant
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install library
      run: pip install .

    - name: Validate JSON-LD files
      run: |
        JSON_FILES=$(find ../../datasets/ -type f -name "*.json")
        for file in ${JSON_FILES}
        do
          echo "Validating ${file}..."
          python scripts/validate.py --file ${file}
        done

  generation-test:
    name: Generation / JSON-LD Tests / Python 3.11
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/ml_croissant
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install library
      run: pip install .

    - name: Generate JSON-LD files - Titanic
      run: python scripts/load.py --file ../../datasets/titanic/metadata.json --record_set passengers

    - name: Generate JSON-LD files - PASS
      run: python scripts/load.py --file ../../datasets/pass-mini/metadata.json --record_set images
